gems:
  - jekyll-paginate-v2
  - jekyll-sitemap

pagination:
  enabled: true
  per_page: 10
  permalink: "/posts/:num.html"
  title: " page :num"
  limit: 0
  sort_field: "date"
  sort_reverse: true
  #paginate_path: "/posts/:num"
  indexpage: "posts"

permalink: "/:year/:month/:title.html"
